### ISSUE TITLE
Cannot test any playbook as it complains of a missing python module

### ISSUE THREAD

**Issue by snevs** [mmumshad/ansible-playable#10]
`info: No config file found; using defaults

POST /api/ansible/execute 201 245.440 ms - 277
error: STDERR: ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'

info: STDOUT: the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 178, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/foreman.py", line 30, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

info: No config file found; using defaults
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 178, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/foreman.py", line 30, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

info: Stream :: close :: code: 250, signal: undefined
info: No config file found; using defaults
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-playbook", line 109, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
    results = pbex.run()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
    self._tqm.load_callbacks()
  File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 178, in load_callbacks
    for callback_plugin in callback_loader.all(class_only=True):
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all
    self._module_cache[path] = self._load_module_source(name, path)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source
    module = imp.load_source(name, path, module_file)
  File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/foreman.py", line 30, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in <module>
    SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

SCRIPT_FINISHED
error: Ansible Execution error = ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'

`

---> pip show pyopenssl
Name: pyOpenSSL
Version: 17.2.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /usr/lib64/python2.7/site-packages
Requires: cryptography, six

**Comment by mmumshad** [comment]
Can you please let me know how you are running the playbook? Were is the Ansible target host? Are you using localhost or any other host?

**Comment by snevs** [comment]
The control host is an Oracle Linux 7.3, and I'm using it against localhost as it doesn't allow me to use different hosts (returns an error when I try to add a different host).

This is the error it shows when I try to add a different host.

![image](https://user-images.githubusercontent.com/18164031/28959598-d030b58e-7903-11e7-9274-db5bb506c3c0.png)

**Comment by mmumshad** [comment]
The control host must have Ansible installed on it.  Is that true in this case?

**Comment by jitender1278** [comment]
yes, it is installed

**Comment by mmumshad** [comment]
Sorry mixed up two conversations.. 

@jitender1278 - Can you please let me know how you are running the playbook? Were is the Ansible target host? Are you using localhost or any other host?

@snevs - The control host must have Ansible installed on it. Is that true in this case?

**Comment by jitender1278** [comment]
yes it has installed

**Comment by jitender1278** [comment]
I mean, it has Ansible

**Comment by snevs** [comment]
@mmumshad Yes, Ansible is installed on the control host
---> ansible --version
ansible 2.3.1.0
  config file = /projects/ansible/playbook/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
  python version = 2.7.5 (default, Sep  5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]

**Comment by snevs** [comment]
What is also sad, is that the ansible package has been updated on the control host without my will:
Ansible had been installed via YUM, and now I see that ansible --version returns a different version
rpm -q ansible
ansible-**2.1.1**.0-1.el7.noarch

ansible --version
ansible **2.3.1**.0
config file = /projects/ansible/playbook/ansible.cfg
configured module search path = [u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
python version = 2.7.5 (default, Sep 5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]

**Comment by jitender1278** [comment]
Thanks for the response, but can you please confirm what shall I do to resolve this

**Comment by mmumshad** [comment]
@snevs We do not perform any package update on the control host. All that it does is try to run the ansible --version command to identify the version of Ansible. From your screenshot I see it is unable to execute ansible command. Have you checked if Ansible command is available with the user you are trying to connect to? In this case - jpamgmt

**Comment by mmumshad** [comment]
@jitender1278  Let us continue your discussion on the other issue #7  you raised.

**Comment by mmumshad** [comment]
@snevs It should be fixed now. I just tested and it works.

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!

**Comment by houstonheat** [comment]
> sudo pip install pyOpenSSL==16.2.0
Same
