### ISSUE TITLE
Demo Issue

### ISSUE THREAD

**Issue by jitender1278** [mmumshad/ansible-playable#7]
hey 

I followed the demo video and created Deploy "Application on GCP" but after play getting this exception

Not sure what I am missing. I tried to create a google GCE

Traceback (most recent call last):
File "/usr/local/bin/ansible-playbook", line 109, in 
exit_code = cli.run()
File "/usr/local/lib/python2.7/dist-packages/ansible/cli/playbook.py", line 154, in run
results = pbex.run()
File "/usr/local/lib/python2.7/dist-packages/ansible/executor/playbook_executor.py", line 89, in run
self._tqm.load_callbacks()
File "/usr/local/lib/python2.7/dist-packages/ansible/executor/task_queue_manager.py", line 178, in load_callbacks
for callback_plugin in callback_loader.all(class_only=True):
File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 415, in all
self._module_cache[path] = self._load_module_source(name, path)
File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/__init__.py", line 338, in _load_module_source
module = imp.load_source(name, path, module_file)
File "/usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/foreman.py", line 30, in 
import requests
File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in 
_attach_namespace(urllib3, 'requests.packages')
File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
module = __import__(name)
File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in 
import OpenSSL.SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in 
from OpenSSL import rand, crypto, SSL
File "/usr/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 105, in 
SSL_ST_INIT = _lib.SSL_ST_INIT
AttributeError: 'module' object has no attribute 'SSL_ST_INIT'

ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'

**Comment by mmumshad** [comment]
Can you please post your playbook here?

**Comment by jitender1278** [comment]
---
# Playbook file: GCP_Demo.yml
-
    name: 'Deploy Application on GCP'
    hosts: localhost
    tags:
        - 'Deploy Application on GCP'
    tasks:
        -
            name: 'deploy compute Engines on GCP'
            gce:
                credentials_file: {}
                name: playable
                num_instances: '2'
                project_id: bbb-feo-77124
                service_account_email: playable@bbb-feo-77124.iam.gserviceaccount.com

**Comment by mmumshad** [comment]
@jitender1278  Have you tried to execute a simple playbook. May be a debug module? I just want to see if the issue for all playbooks or specific to GCP. Also please share a screenshot of your projects page, showing the project name and Ansible controller host details.

**Comment by fubarhouse** [comment]
Also experiencing this.

Zero complexity here, and I can't even create custom roles.

![image](https://user-images.githubusercontent.com/3070264/29054240-516a43ea-7c38-11e7-8e77-822c30b39e7b.png)

And if that wasn't bad enough (cause it's not), I can't execute any playbook... It doesn't even start.

![image](https://user-images.githubusercontent.com/3070264/29054267-8dbd1c14-7c38-11e7-86fe-41e705c8b0ce.png)

**Comment by fubarhouse** [comment]
Also, I have fixed this one by running the following command on the container.
````pip install pyOpenSSL==16.2.0````

I shall submit a PR tonight updating the Dockerfile ***only*** if you're interested, my involvement is otherwise complete - but somebody should address this.

**Comment by mmumshad** [comment]
Ah, thank you very much! Appreciate it!  I must have missed that module from the Dockerfile.

**Comment by mmumshad** [comment]
This should be fixed now. @jitender1278 Can you please pull latest docker image and test?

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
